---
abstract: 'TypeKey authentication'
author:
  - 'zdk ( Warachet Samtalee )'
build_requires:
  Catalyst::Runtime: 0
  ExtUtils::MakeMaker: 6.42
  Test::MockObject: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Credential-TypeKey
no_index:
  directory:
    - inc
    - t
requires:
  Authen::TypeKey: 0
  Catalyst::Exception: 0
  Catalyst::Plugin::Authentication: 0
  Moose: 0
  MooseX::Types::Common::String: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/zdk/catalyst-authentication-credential-typekey.git
version: 0.004
